import { IBiography } from "../interfaces/IBiography";

const biographies: IBiography[] = [
  {
    _id: "",
    year: "2021",
    title:
      "A Força Pública em Mato Grosso e a formação do Corpo Policial no período imperial",
    typeBiography: "empire",
    typeProduction: "thesis",
    nameProduction: "UNISINOS",
    nameAuthor: "David Campos Martins",
    lastNameAuthor: "Martins",
    organizers: [],
    country: "Brasil",
    city: "São Leopoldo",
    state: { name: "Rio Grande do Sul", abbreviation: "RS" },
    link: "http://www.repositorio.jesuita.org.br/handle/UNISINOS/10303",
    searched: undefined,
  },
  {
    _id: "",
    year: "2021",
    title:
      "Administrando a (in)segurança: experiências de conflito e negociação da chefatura de polícia na sociedade oitocentista cearense",
    typeBiography: "empire",
    typeProduction: "thesis",
    nameProduction: "UNISINOS",
    nameAuthor: "Patrícia Marciano de Assis",
    lastNameAuthor: "Assis",
    organizers: [],
    country: "Brasil",
    city: "Recife",
    state: { name: "Pernambuco", abbreviation: "PE" },
    link: "https://repositorio.ufpe.br/handle/123456789/44504",
    searched: undefined,
  },
  {
    _id: "",
    year: "2021",
    title: "A polícia na Corte Imperial: mesclas entre a inovação e a tradição",
    typeBiography: "empire",
    typeProduction: "book",
    nameProduction: "Editora Letra 1",
    nameAuthor: "Joice de Souza Soares",
    lastNameAuthor: "Soares",
    organizers: [],
    country: "Brasil",
    city: "Porto Alegre",
    state: { name: "Rio Grande do Sul", abbreviation: "RS" },
    link: "https://www.editoraletra1.com.br/epub/9786587422121",
    searched: undefined,
  },
  {
    _id: "",
    year: "2019",
    title:
      "Polícia(s) em São Paulo: a Guarda Municipal permanente e as Guardas Policiais (1834-1850)",
    typeBiography: "empire",
    typeProduction: "dissertation",
    nameProduction: "UNIFESP",
    nameAuthor: "Bruna Prudêncio Texeira",
    lastNameAuthor: "Texeira",
    organizers: [],
    country: "Brasil",
    city: "Guarulhos",
    state: { name: "São Paulo", abbreviation: "SP" },
    link: "https://repositorio.unifesp.br/handle/11600/59816",
    searched: undefined,
  },
  {
    _id: "",
    year: "2018",
    title:
      "Guarda Real da Polícia do Rio de Janeiro: um estudo sobre as atribuições da primeira instituição ostensiva brasileira",
    typeBiography: "empire",
    typeProduction: "dissertation",
    nameProduction: "UNIRIO",
    nameAuthor: "André Luís Cardoso Azoubel Zulli",
    lastNameAuthor: "Zulli",
    organizers: [],
    country: "Brasil",
    city: "Rio de Janeiro",
    state: { name: "Rio de Janeiro", abbreviation: "RJ" },
    link: "http://www.repositorio-bc.unirio.br:8080/xmlui/handle/unirio/11626",
    searched: undefined,
  },
  {
    _id: "",
    year: "2017",
    title:
      "A silhueta do poder: os escravos Balbina e Benedito – prática policial, administração da justiça e violência no regime escravista em Cuiabá e sua zona serrana (1840-1888)",
    typeBiography: "empire",
    typeProduction: "dissertation",
    nameProduction: "UFMT",
    nameAuthor: "José Carlos H. B. C. dos Reis",
    lastNameAuthor: "Reis",
    organizers: [],
    country: "Brasil",
    city: "Cuiabá",
    state: { name: "Mato Grosso", abbreviation: "MT" },
    link: undefined,
    searched: undefined,
  },
  {
    _id: "",
    year: "2017",
    title:
      "Eusébio de Queirós e a chefia de Polícia da Corte: um laboratório Saquarema (1830-1840)",
    typeBiography: "empire",
    typeProduction: "dissertation",
    nameProduction: "UFF",
    nameAuthor: "Felipe Pessanha de Almeida",
    lastNameAuthor: "Almeida",
    organizers: [],
    country: "Brasil",
    city: "Rio de Janeiro",
    state: { name: "Rio de Janeiro", abbreviation: "RJ" },
    link: "https://app.uff.br/riuff/handle/1/13684",
    searched: undefined,
  },
  {
    _id: "",
    year: "2016",
    title:
      "Palácio das misérias: populares, delegados e carcereiros em Pelotas (1869-1889)",
    typeBiography: "empire",
    typeProduction: "book",
    nameProduction: "Oikos",
    nameAuthor: "Caiuá Cardoso Al-Alam",
    lastNameAuthor: "Al-Alam",
    organizers: [],
    country: "Brasil",
    city: "São Leopoldo",
    state: { name: "Rio Grande do Sul", abbreviation: "RS" },
    link: undefined,
    searched: undefined,
  },
  {
    _id: "",
    year: "2014",
    title: "Eusébio de Queirós: chefe de polícia da Corte (1833-1844)",
    typeBiography: "empire",
    typeProduction: "dissertation",
    nameProduction: "UERJ",
    nameAuthor: "Welinton Serafim da Silva",
    lastNameAuthor: "Silva",
    organizers: [],
    country: "Brasil",
    city: "Rio de Janeiro",
    state: { name: "Rio de Janeiro", abbreviation: "RJ" },
    link: "https://www.bdtd.uerj.br:8443/handle/1/13155",
    searched: undefined,
  },
  {
    _id: "",
    year: "2014",
    title:
      "Entre a liturgia e o salário: a formação dos aparatos policiais no Recife do século XIX (1830-1850)",
    typeBiography: "empire",
    typeProduction: "book",
    nameProduction: "Paco Editorial",
    nameAuthor: "Wellington Barbosa Silva",
    lastNameAuthor: "Silva",
    organizers: [],
    country: "Brasil",
    city: "Jundiaí",
    state: { name: "São Paulo", abbreviation: "SP" },
    link: undefined,
    searched: undefined,
  },
  {
    _id: "",
    year: "2021",
    title:
      "Sherlock Holmes no Brasil: Elysio de Carvalho e a construção da polícia científica: Rio de Janeiro 1907-1915",
    typeBiography: "republic",
    typeProduction: "book",
    nameProduction: "PUC-RIO",
    nameAuthor: "Marília Rodrigues de Oliveira",
    lastNameAuthor: "Oliveira",
    organizers: [],
    country: "Brasil",
    city: "Rio de Janeiro",
    state: { name: "Rio de Janeiro", abbreviation: "RJ" },
    link: "http://www.editora.puc-rio.br/media/Sherlock%20Holmes%20no%20Brasil_book%20(1).pdf",
    searched: undefined,
  },
  {
    _id: "",
    year: "2018",
    title:
      "A guerra das ruas: povo e polícia na cidade do Rio de Janeiro (2a ed.)",
    typeBiography: "republic",
    typeProduction: "book",
    nameProduction: "Gramma",
    nameAuthor: "Marcos Luiz Bretas",
    lastNameAuthor: "Bretas",
    organizers: [],
    country: "Brasil",
    city: "Rio de Janeiro",
    state: { name: "Rio de Janeiro", abbreviation: "RJ" },
    link: undefined,
    searched: undefined,
  },
  {
    _id: "",
    year: "2014",
    title:
      "A Civilização do Delegado: modernidade, polícia e sociedade em São Paulo nas primeiras décadas da República, 1889-1930",
    typeBiography: "republic",
    typeProduction: "book",
    nameProduction: "Alameda",
    nameAuthor: "Marcelo Thadeu Quintanilha Martins",
    lastNameAuthor: "Martins",
    organizers: [],
    country: "Brasil",
    city: "São Paulo",
    state: { name: "São Paulo", abbreviation: "SP" },
    link: undefined,
    searched: undefined,
  },
  {
    _id: "",
    year: "2018",
    title:
      "The men of Mobtown: policing Baltimore in the age of slavery and emancipation",
    typeBiography: "others",
    typeProduction: "book",
    nameProduction: "University of North Carolina Press",
    nameAuthor: "Adam Malka",
    lastNameAuthor: "Malka",
    organizers: [],
    country: "Estados Unidos",
    city: undefined,
    state: { name: "North Carolina", abbreviation: "NC" },
    link: undefined,
    searched: undefined,
  },
  {
    _id: "",
    year: "2015",
    title:
      "Policing Slavery: Order and the development of Early Nineteenth-Century New Orleans and Salvador",
    typeBiography: "others",
    typeProduction: "dissertation",
    nameProduction: "Florida International University",
    nameAuthor: "Gregory K. Weimer",
    lastNameAuthor: "Weimer",
    organizers: [],
    country: "Estados Unidos",
    city: undefined,
    state: { name: "Flórida", abbreviation: "FL" },
    link: "https://digitalcommons.fiu.edu/cgi/viewcontent.cgi?article=3233&context=etd",
    searched: undefined,
  },
  {
    _id: "",
    year: "2023",
    title: "História da Polícia no Brasil",
    typeBiography: "others",
    typeProduction: "magazine",
    nameProduction: "Saeculum UFPB",
    nameAuthor: undefined,
    lastNameAuthor: undefined,
    organizers: [
      { nameAuthor: "Marcos Luiz Bretas", lastNameAuthor: "Bretas" },
      { nameAuthor: "Wellington Barbosa Silva", lastNameAuthor: "Silva" },
    ],
    country: "Brasil",
    city: "João Pessoa",
    state: { name: "Paraíba", abbreviation: "PA" },
    link: "https://periodicos.ufpb.br/index.php/srh/issue/view/2890",
    searched: undefined,
  },
  {
    _id: "",
    year: "2020",
    title: "Polícia, justiça e prisões: estudos históricos",
    typeBiography: "others",
    typeProduction: "magazine",
    nameProduction: "Appris",
    nameAuthor: undefined,
    lastNameAuthor: undefined,
    organizers: [
      { nameAuthor: "Marcos Luiz Bretas", lastNameAuthor: "Bretas" },
      { nameAuthor: "Tiago da Silva César", lastNameAuthor: "César" },
      { nameAuthor: "Pedro Oliver Olmo", lastNameAuthor: "Olmo" },
    ],
    country: "Brasil",
    city: "Curitiba",
    state: { name: "Paraná", abbreviation: "PR" },
    link: undefined,
    searched: undefined,
  },
];
